### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by adityosnrost** [liarjo/MediaBlutlerTest01#3]
Hi,

I would like to know about Media Butler Storage. When installing Media Butler, we put Media services storage account name and Media services storage account key that we had. After installing Media Butler, we get new Resources Group with app services and also new Media Service Storage.

What are the differences of Storage that we input within installation and the new one that created after installing Media Butler ?

Thanks

Best Regards,

Adityo Setyonugroho

**Comment by liarjo** [comment]
Hello,

you have 2 Azure Storage account to keep in mind. 
First, Azure Media Services Storage account. this is the storage account use by Azure Media services.
Second, Staging storage use by Media Butler. it is on this storage, staging storage, where you will upload the new videos to be manage by Media Butler framework.

let me know if you have any other question or comments,

JuanPablo

**Comment by adityosnrost** [comment]
Hello,

Sorry for my late reply. Thank you for your reply. I get it now. Can I use the same storage for both MBF and AMS ?

**Comment by liarjo** [comment]
yes, you can use one but the recommendation is use 2 different.
